# Generated by Django 4.1.5 on 2023-01-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=20, verbose_name='Asunto')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('file', models.FileField(upload_to='', verbose_name='Archivos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado')),
                ('status', models.CharField(choices=[('Pending', 'pending'), ('Read', 'read')], max_length=50, verbose_name='Estado')),
            ],
        ),
    ]
